version: '2'
services:
    pg:
      image: postgres:11.9
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
